# Configuration

# -------- Location --------
# Location in latitude and longitude coordinates
lat: 53.524960
lon: -1.627447

# Format: YYYYMMDD
start_date: 20000101

# Format: YYYYMMDD
end_date: 20210101

# Output directory for weather records
output_dir: ./data
